FROM ghcr.io/foundry-rs/foundry:latest

WORKDIR /app

COPY . .

USER root
RUN chmod +x docker-entrypoint.sh

ENTRYPOINT ["/bin/sh", "-c", "anvil --host 0.0.0.0 --port 8545 --allow-origin '*' --chain-id 31337 --gas-price 1"]
